### ISSUE TITLE
encounter a bug 

### ISSUE THREAD

**Issue by sunnyHelen** [xiaoaoran/SemanticSTF#2]
Hi, thanks for sharing your great work. 
I am trying to reproduce and follow your research. But there is a bug when I try to train. I am new to this area. Could you please check it:
[2023-09-04 18:59:19.072] Epoch 1/50 started.
  0% 0/4783 [00:00<?, ?it/s]/project/RDS-FEI-HMZDet-RW/pointdr3/lib/python3.7/site-packages/torchsparse/nn/functional/conv.py:117: UserWarning: This overload of nonzero is deprecated:
        nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
        nonzero(Tensor input, *, bool as_tuple) (Triggered internally at  /usr/local/src/PYTORCH/27-apr-2020/pytorch/torch/csrc/utils/python_arg_parser.cpp:760.)
  nbmaps = torch.nonzero(results != -1)
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    main()
  File "train.py", line 103, in main
    Saver(),
  File "/project/RDS-FEI-HMZDet-RW/pointdr3/lib/python3.7/site-packages/torchpack/train/trainer.py", line 39, in train_with_defaults
    callbacks=callbacks)
  File "/project/RDS-FEI-HMZDet-RW/SemanticSTF-master/PointDR/core/trainers.py", line 183, in train
    output_dict = self.run_step(feed_dict)
  File "/project/RDS-FEI-HMZDet-RW/pointdr3/lib/python3.7/site-packages/torchpack/train/trainer.py", line 125, in run_step
    output_dict = self._run_step(feed_dict)
  File "/project/RDS-FEI-HMZDet-RW/SemanticSTF-master/PointDR/core/trainers.py", line 75, in _run_step
    pred_2, feat_2 = self.model(inputs_2)
  File "/usr/local/python/3.7.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 562, in __call__
    result = self.forward(*input, **kwargs)
  File "/project/RDS-FEI-HMZDet-RW/SemanticSTF-master/PointDR/core/models/semantic_kitti/minkunet_dr.py", line 201, in forward
    x2 = self.stage2(x1)
  File "/usr/local/python/3.7.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 562, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/python/3.7.7/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/python/3.7.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 562, in __call__
    result = self.forward(*input, **kwargs)
  File "/project/RDS-FEI-HMZDet-RW/SemanticSTF-master/PointDR/core/models/semantic_kitti/minkunet_dr.py", line 74, in forward
    out = self.relu(self.net(x) + self.downsample(x))
  File "/usr/local/python/3.7.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 562, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/python/3.7.7/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/python/3.7.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 562, in __call__
    result = self.forward(*input, **kwargs)
  File "/project/RDS-FEI-HMZDet-RW/pointdr3/lib/python3.7/site-packages/torchsparse/nn/modules/conv.py", line 72, in forward
    transposed=self.transposed)
  File "/project/RDS-FEI-HMZDet-RW/pointdr3/lib/python3.7/site-packages/torchsparse/nn/functional/conv.py", line 98, in conv3d
    feats = feats.matmul(weight)
RuntimeError: expected scalar type Half but found Float

**Comment by sunnyHelen** [comment]
Caused by amp issues. Solved.
